uImage wrapper needs to extract binary from vmlinux (elf)

diff --git a/90-uImage.install b/90-uImage.install
--- a/90-uImage.install
+++ b/90-uImage.install
@@ -6,36 +6,51 @@ echo "ARGS: $*"
 echo "VER: $VER"
 echo "KERNEL: $KERNEL"
 
+# Option 1, wrap uImage manually
 # uImage compression options: none, bzip2, gzip, lz4, lzma, lzo, zstd
-FCOMP="$(file -i "${ENTRY_DIR_ABS}/linux")"
-if echo "$FCOMP" | grep -q gzip; then
-	echo "Detected gzip kernel"
-	COMP="gzip"
-elif echo "$FCOMP" | grep -q bzip2; then
-	echo "Detected bzip2 kernel"
-	COMP="bzip2"
-elif echo "$FCOMP" | grep -q lzma; then
-	echo "Detected lzma kernel"
-	COMP="lzma"
-elif echo "$FCOMP" | grep -q lz4; then
-	echo "Detected lz4 kernel"
-	COMP="lz4"
-elif echo "$FCOMP" | grep -q zstd; then
-	echo "Detected zstd kernel"
-	COMP="zstd"
-else
-	echo "Assuming uncompressed kernel"
-	COMP="none"
+FCOMP="$(file -i "$KERNEL")"
+if echo "$FCOMP" | ! grep -q executable; then
+  echo "Error: vmlinux needs to be decompressed"
+	exit 1
 fi
+#if echo "$FCOMP" | grep -q gzip; then
+#	echo "Detected gzip kernel"
+#	gzip -d "$KERNEL"
+#elif echo "$FCOMP" | grep -q bzip2; then
+#	echo "Detected bzip2 kernel"
+#	bzip2 -d "$KERNEL"
+#elif echo "$FCOMP" | grep -q lzma; then
+#	echo "Detected lzma kernel"
+#	lzma -d "$KERNEL"
+#elif echo "$FCOMP" | grep -q lz4; then
+#	echo "Detected lz4 kernel"
+#	lz4 -d "$KERNEL"
+#elif echo "$FCOMP" | grep -q zstd; then
+#	echo "Detected zstd kernel"
+#	zstd -d "$KERNEL"
+#else
+#	echo "Assuming uncompressed kernel"
+#fi
 
-# if none, compress with gzip
-IN="$KERNEL"
-if [[ "$COMP" == "none" ]]; then
-	IN=$(mktemp)
-	gzip --best -c "$KERNEL" > "$IN"
-	COMP="gzip"
-fi
+# extract binary from vmlinux (elf)
+IN=$(mktemp)
+objcopy -O binary "$KERNEL" "$IN"
+
+# default: compress with gzip
+gzip --best "$IN"
+IN="$IN.gz"
+COMP="gzip"
+
 
 # wrap (compressed) vmlinux as uImage
-mkimage -A powerpc -O linux -T kernel -C "${COMP}" -a 0 -e 0 -n "Gentoo Linux ${VER}" -d "${IN}" "${KERNEL/vmlinux/uImage}"
+ofile="${KERNEL/vmlinux/uImage}"
+membase=`objdump -p "$KERNEL" | grep -m 1 LOAD | awk '{print $7}'`
+rm -f "$ofile"
+mkimage -A powerpc -O linux -T kernel -C "$COMP" -a "$membase" -e "$membase" -n "Gentoo Linux $VER" -d "$IN" "$ofile"
+rm -f "$IN"
+
+
+# Option 2, leverge kernel's uboot wrapper
+# mimiking arch/powerpc/boot/.uImage.cmd generated during make uImage
+#"${srcdir}/arch/powerpc/boot/wrapper" -Z gz -c -o "${KERNEL/vmlinux/uImage}" -p uboot "${IN}"
 
